"""Promote one canonical detector run from staging into regression output."""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


def _read_json(path: Path) -> dict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return payload


def _merge_tree(source: Path, target: Path) -> None:
    if not source.is_dir():
        return
    target.mkdir(parents=True, exist_ok=True)
    for item in source.iterdir():
        destination = target / item.name
        if item.is_dir():
            _merge_tree(item, destination)
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(item, destination)


def finalize_run(
    *,
    canonical_run: Path,
    staging_root: Path,
    output_root: Path,
    detector: str,
) -> Path:
    """Publish canonical run/debug/results identically for 1 or N shards.

    Shard count affects how ``canonical_run`` is produced, never how it is
    published.  All artifact-visible promotion belongs here.
    """
    canonical_run = canonical_run.resolve()
    staging_root = staging_root.resolve()
    output_root = output_root.resolve()

    manifest_path = canonical_run / "manifest.json"
    if not manifest_path.is_file():
        raise ValueError(f"Canonical run is missing manifest.json: {canonical_run}")
    manifest = _read_json(manifest_path)
    manifest_detector = str(manifest.get("detector") or "")
    if manifest_detector != detector:
        raise ValueError(
            f"Canonical detector mismatch: expected {detector!r}, "
            f"manifest has {manifest_detector!r}"
        )
    run_id = str(manifest.get("run_id") or canonical_run.name)
    if canonical_run.name != run_id:
        raise ValueError(
            f"Canonical run directory/name mismatch: directory={canonical_run.name!r}, "
            f"manifest run_id={run_id!r}"
        )

    target_parent = output_root / detector
    target_parent.mkdir(parents=True, exist_ok=True)
    target_run = target_parent / run_id
    if target_run.exists():
        raise FileExistsError(f"Canonical target already exists: {target_run}")

    # Debug is intentionally outside the run directory. Promote only this
    # detector/run subtree so stale or unrelated staged evidence cannot leak.
    staged_debug = staging_root / "debug" / detector / run_id
    if staged_debug.is_dir():
        target_debug = output_root / "debug" / detector / run_id
        if target_debug.exists():
            raise FileExistsError(f"Debug target already exists: {target_debug}")
        target_debug.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(staged_debug), str(target_debug))

    # Preserve the detector-level convenience ranking generated by both the
    # normal runner and shard merger when present.
    staged_ranking = canonical_run.parent / f"{detector}-regression-results.csv"
    if staged_ranking.is_file():
        ranking_target = target_parent / staged_ranking.name
        if ranking_target.exists():
            ranking_target.unlink()
        shutil.move(str(staged_ranking), str(ranking_target))

    shutil.move(str(canonical_run), str(target_run))
    return target_run


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--canonical-run", type=Path, required=True)
    parser.add_argument("--staging-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--detector", required=True)
    args = parser.parse_args(argv)
    print(finalize_run(
        canonical_run=args.canonical_run,
        staging_root=args.staging_root,
        output_root=args.output,
        detector=args.detector,
    ))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
