name: HTH Calibration
on: {workflow_dispatch: {}}
jobs:
  pipeline:
    uses: ./.github/workflows/_core-hth.yml
    with:
      mode: calibration
      process_limit: calibration
      run_preprocess: false
      run_detect: true
      run_validate: true
      run_publish: true
