name: HTH Production
on: {workflow_dispatch: {}, push: {branches: [main]}}
jobs:
  pipeline:
    uses: ./.github/workflows/_core-hth.yml
    with:
      mode: production
      process_limit: all
      run_preprocess: true
      run_detect: true
      run_validate: true
      run_publish: true
